export const PERMISSIONS = {
    // Institutions
    DELETE_INSTITUTION: 'DELETE_INSTITUTION',
    UPDATE_INSTITUTION: 'UPDATE_INSTITUTION',
    VIEW_ONLY_INSTITUTIONS: 'VIEW_ONLY_INSTITUTIONS',
    CREATE_INSTITUTIONS: 'CREATE_INSTITUTIONS',

    CREATE_ROLE: "CREATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    VIEW_ONLY_ROLES: "VIEW_ONLY_ROLES",

    CREATE_USER: "CREATE_USER",
    DELETE_USER: "DELETE_USER",
    UPDATE_USER: "UPDATE_USER",
    VIEW_ONLY_USERS: "VIEW_ONLY_USERS",

    // Applications
    CREATE_APPLICATIONS: "CREATE_APPLICATIONS",
    DELETE_APPLICATION: "DELETE_APPLICATION",
    UPDATE_APPLICATION: "UPDATE_APPLICATION",
    VIEW_ONLY_APPLICATIONS: "VIEW_ONLY_APPLICATIONS",

    CREATE_PERMISSION: "CREATE_PERMISSION",
    DELETE_PERMISSION: "DELETE_PERMISSION",
    UPDATE_PERMISSION: "UPDATE_PERMISSION",
    VIEW_ONLY_PERMISSIONS: "VIEW_ONLY_PERMISSIONS",
};
