-- AlterTable
ALTER TABLE `auditlog` MODIFY `action` ENUM('REGISTER', 'LOGIN', 'LOGOUT', 'LOGOUTALL', 'REFRESH_TOKEN', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'CHANGE_PASSWORD', 'FORGOT_PASSWORD', 'RESET_PASSWORD', 'VERIFY_EMAIL', 'REVOKE_SESSION') NOT NULL;
