export default Object.freeze({

    IP: process.env.IP,
    APP_URL: process.env.APP_URL,

    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,

    NODE_ENV: process.env.NODE_ENV,
    PORT: Number(process.env.PORT),
    DATABASE_URL: process.env.DATABASE_URL,

    JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,

    JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
    JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,
    TWO_FACTOR_SECRET_KEY: process.env.TWO_FACTOR_SECRET_KEY,

    ACCESS_TOKEN_ISSUER: process.env.ACCESS_TOKEN_ISSUER,
    ACCESS_TOKEN_AUDIENCE: process.env.ACCESS_TOKEN_AUDIENCE,

    SESSION_EXPIRES_IN: process.env.SESSION_EXPIRES_IN,
    SESSION_CLEANUP_INTERVAL: process.env.SESSION_CLEANUP_INTERVAL,

    REFRESH_TOKEN_ROTATION: process.env.REFRESH_TOKEN_ROTATION === 'true',

    LOGIN_MAX_FAILED_ATTEMPTS: Number(process.env.LOGIN_MAX_FAILED_ATTEMPTS),
    LOGIN_LOCK_MINUTES: Number(process.env.LOGIN_LOCK_MINUTES),

    BCRYPT_ROUNDS: Number(process.env.BCRYPT_ROUNDS),
    CLIENT_URL: process.env.CLIENT_URL,
    IDEMPOTENCY_TTL: Number(process.env.IDEMPOTENCY_TTL),
    PASSWORD_MIN_LENGTH: Number(process.env.PASSWORD_MIN_LENGTH),
    PASSWORD_HISTORY_LIMIT: Number(process.env.PASSWORD_HISTORY_LIMIT),
    PASSWORD_RESET_TOKEN_EXPIRES_IN: process.env.PASSWORD_RESET_TOKEN_EXPIRES_IN,
    REVOKE_SESSIONS_ON_PASSWORD_CHANGE: process.env.REVOKE_SESSIONS_ON_PASSWORD_CHANGE === 'true',
    REMEMBER_ME_EXPIRES_IN: process.env.REMEMBER_ME_EXPIRES_IN,
    OTP_EXPIRES_IN: process.env.OTP_EXPIRES_IN,
    APP_NAME: process.env.APP_NAME,
    APP_VERSION: process.env.APP_VERSION,

    STORAGE_LOCATION: process.env.STORAGE_LOCATION,
    APPLICATION_LOGO_STORAGE: process.env.APPLICATION_LOGO_STORAGE,
    INSTITUTION_LOGO_STORAGE: process.env.INSTITUTION_LOGO_STORAGE,
    
    ALLOWED_CALLBACK_DOMAINS: process.env.ALLOWED_CALLBACK_DOMAINS?.split(',').map(domain => domain.trim()) || [],
});