export default Object.freeze({
    MAX_LOGIN_ATTEMPTS:5,
    ACCOUNT_LOCK_MINUTES:15,
    PASSWORD_RESET_MINUTES:15,
    EMAIL_VERIFICATION_HOURS:24,
    ACCESS_TOKEN_MINUTES:15,
    REFRESH_TOKEN_DAYS:30
});